#!/usr/bin/env bash
cd /home/despegar/com.reservalia.api
args=("$@")
port=${args[0]}
now=$(date +"%Y-%m-%d-%T")
host=`hostname`
DB_HOST=reservalia-prod-00:27017,reservalia-prod-01:27017 NODE_ENV="production" forever --uid "${host}" -l "${host}-${now}.log" start app.js