#!/usr/bin/env bash
cd /home/despegar/com.reservalia.api
args=("$@")
port=${args[0]}
now=$(date +"%Y-%m-%d-%T")
host=`hostname`
DEBUG=* NODE_ENV="production" forever --uid "${host}" -l "${host}-${now}.log" start app.js